version: "2.19.1"
services:
    database:
        image: mysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_DATABASE: adrora
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD:  root
        volumes:
            - ./database:/docker-entrypoint-initdatabase.d
        networks:
            - default
    web:
        build: .
        ports: 
            - 8080:80
        volumes:
            - ./public:/var/web/html
        links:
            - database
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - database
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
